### ISSUE TITLE
Rails 5.2 with bundle install

### ISSUE THREAD

**Issue by flyfy1** [salsify/goldiloader#65]
In the gemfile, it states that it requires rails version < 5.2 <https://github.com/salsify/goldiloader/blob/master/goldiloader.gemspec#L26>

Therefore, it would fail the rails v5.2 when doing bundle install, having the following error:

```
Fetching gem metadata from https://rubygems.org/......
Fetching source index from https://rubygems.org/
Resolving dependencies............................................
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    annotate was resolved to 2.7.2, which depends on
      activerecord (< 6.0, >= 3.2)

    goldiloader was resolved to 0.0.4, which depends on
      activerecord (<= 4.1, >= 3.2)

    paper_trail was resolved to 9.0.0, which depends on
      activerecord (< 5.3, >= 4.2)

    paranoia was resolved to 1.2.0, which depends on
      activerecord (>= 3.0.0)

    rails was resolved to 5.2.0, which depends on
      activerecord (= 5.2.0)
```

strangely, this error only happens since today.

What's the reason for this gem to require rails version < 5.2 ?

Thanks 😄

**Comment by jturkel** [comment]
The gem use fairly pessimistic Rails version constraints because it leverages a few internal APIs that change from minor release to minor release. I like to make sure all tests are passing before releasing a version with official support for a new major/minor release of Rails. You can follow  the status of Rails 5.2 support in #63.
